### ISSUE TITLE
Group write permission for the `translations` dir

### ISSUE THREAD

**Issue by asprega** [willdurand/BazingaJsTranslationBundle#111]
I was wondering why, when dumping the translations, the `translations` dir doesn't get the g+w permission.
In other words: if I dump the translation as a given user, then I try to do it again as a different user, I get the following error:

`[Symfony\Component\Filesystem\Exception\IOException]      
  Failed to remove file "web/js/translations/messages/en.js".`

This could be useful in at least two multi-user situations I can think of:
a) a shared doc-root, where multiple developers would want to run commands
b) a non-shared doc-root which is used e.g. by a developer and a jenkins instance

Is this a requirement that can be accepted? If so, would you hardcode the new permission bitmask in code or make it configurable? I could create a pull request for that.

**Comment by asprega** [comment]
I might be wrong here, but based on this line of code in the `TranslationDumper`: `$this->filesystem->mkdir(dirname($file), 0755);` I don't think I can do anything with the umask. If it was 0777 I could have used the umask to tune the permissions. What about updating that value to `0777`? Or do you have any other suggestions other than hacking up a console command to fix permissions?

**Comment by stof** [comment]
@willdurand the bundle should indeed use 0777 to let the umask control it. If it uses 0775 or 0755, it controls it itself instead of letting the system control it.

**Comment by willdurand** [comment]
@asprega @stof I pushed a quick fix, let me know.

**Comment by asprega** [comment]
Great! I found another two occurrences where the 0755 mode should be removed imho:

https://github.com/willdurand/BazingaJsTranslationBundle/blob/9064423df5c13aa989effdced01264ed3d2a24cb/Dumper/TranslationDumper.php#L185

https://github.com/willdurand/BazingaJsTranslationBundle/blob/61b8c50ed78f20fc592525b2ad1ecee99060fd92/Tests/Dumper/TranslationDumperTest.php#L27 (this one is not necessary but may be good for consistency)

What do you think?

**Comment by willdurand** [comment]
@asprega would you mind create a PR? I think it would be better to remove all occurences.

**Comment by asprega** [comment]
sure!

**Comment by asprega** [comment]
Thanks for merging! Looking forward to a tagged release including this.
