### ISSUE TITLE
BazingaJsTranslationBundle does not translate strings

### ISSUE THREAD

**Issue by paquitodev** [willdurand/BazingaJsTranslationBundle#122]
I'm trying to use [BazingaJsTranslationBundle][1] for take advance of Symfony2 translations. After read docs this is what I've done:

 1. Include needed JS libraries

		<script src="{{ asset('bundles/bazingajstranslation/js/translator.min.js') }}"></script>
        // Tried this way
		<script src="{{ url('bazinga_jstranslation_js', { 'domain': 'AppBundle' }) }}"></script>

        // Also tried this one
		<script src="{{ url('bazinga_jstranslation_js') }}"></script>

 2. Setup bundle at `config.yml`:

		bazinga_js_translation:
		    locale_fallback:      "%locale%"
		    default_domain:       AppBundle

 3. Dump translations using the bazinga supply command:

		Symfony > bazinga:js-translation:dump
		Installing translation files in /var/www/html/sencamer.dev/web/js directory

 4. Start using translations in JS files:

		Translator.trans('mensaje.msgAgregarSatisfactorio', {"pronombre": "la", "elemento": "solicitud"}, 'AppBundle')

    where this is the original string from `AppBundle.es.yml`:

    	msgAgregarSatisfactorio: Se ha creado %pronombre% %elemento% satisfactoriamente.

    and this is the dump translation at `web\js\translations\AppBundle\es.js`

		Translator.add("mensajes.msgAgregarSatisfactorio", "Se ha creado %pronombre% %elemento% satisfactoriamente.", "AppBundle", "es");

When that code is executed I get the untranslated string: `mensaje.msgAgregarSatisfactorio` but not the message, why? What's wrong? This topic is related to [this one][2] in somehow, any advice?

 [1]: https://github.com/willdurand/BazingaJsTranslationBundle
 [2]: http://stackoverflow.com/questions/26814240/weird-issue-translations-works-if-logged-in-if-not-then-didnt-work-in-symfony

**Comment by herodrigues** [comment]
Tried exactly how you have described here and it worked.

**Comment by willdurand** [comment]
@paquitodev still an issue?

**Comment by paquitodev** [comment]
@willdurand nope, it works now after follow @herodrigues steps slowly, thanks both of yours

**Comment by willdurand** [comment]
thanks!

**Comment by ApezoumonElomProd** [comment]
I have text in french and try to translate in english; but not work.

**Comment by stof** [comment]
@ApezoumonElomProd please don't comment on unrelated closed issues.

Btw, I think you misunderstood totally what this package is about. It is not about translating arbitrary text.

**Comment by ApezoumonElomProd** [comment]
@stof ok. I found the solution. i use this package in symfony project not arbitrary text.
