### ISSUE TITLE
Locale not allowed

### ISSUE THREAD

**Issue by fcharrier** [willdurand/BazingaJsTranslationBundle#130]
Hi,

since 2.1.3 version, one of our locale is not supported by JsTranslationBundle.
It's a locale added for a specific customer: fr_ctm
A fix has been added in 2.1.4, but it still does not allow fr_ctm: https://github.com/willdurand/BazingaJsTranslationBundle/issues/119

Is it "normal" to refuse a locale like "fr_ctm"? Why? Is it linked to standard country codes, limited to 2 characters? (Alpha-2 codes, cf. http://en.wikipedia.org/wiki/ISO_3166-1#Current_codes)

Thanks,
Fred

**Comment by willdurand** [comment]
Yes it is, and it is also security related, because not restricting the locale format would lead to security issues.

**Comment by fcharrier** [comment]
Ok, thank you for your response
