### ISSUE TITLE
Translation extractor

### ISSUE THREAD

**Issue by JANorman** [willdurand/BazingaJsTranslationBundle#131]
Hi, is there any extractor available for this bundle to work with ExtractorInterface?

Thanks

**Comment by willdurand** [comment]
What do you mean?

**Comment by JANorman** [comment]
Apologies for the lack of context! JMSTranslationBundle currently has
extractors for PHP and Twig templates. Are there any plans to have an
extractor for JS files? This is something we may look in to if not...

**Comment by willdurand** [comment]
Ah I see. Nope, not planned.

**Comment by jcchavezs** [comment]
I just opened a PR for this https://github.com/willdurand/BazingaJsTranslationBundle/pull/164
cc/ @JANorman @willdurand
