### ISSUE TITLE
[RFC] Allow translations from view

### ISSUE THREAD

**Issue by rvanlaak** [willdurand/BazingaJsTranslationBundle#145]
I'm not completely sure yet or this is something that could be supported by this bundle, but wat about improving the Javascript translator to support translations from the view? Currently the bundle only exposes translations, is editing them something you'd like to support in the near future?

First thing to overcome should be to wrap translations into a `<span>`, and thereafter the Translator could make use of http://createjs.org/ to do translations. Did ask a question about that already: http://stackoverflow.com/questions/31314427/wrap-translator-trans-and-transchoice-function-output-into-span

Next, an endpoint to save the new translation should be added. Is this something this bundle can handle?

**Comment by stof** [comment]
IMO, a UI to manage translations is out of the scope of this bundle. It is a totally different feature.

**Comment by willdurand** [comment]
Yep. Look at http://openl10n.io/ maybe.

**Comment by rvanlaak** [comment]
I agree :+1: thanks for the link @willdurand
