### ISSUE TITLE
Lack of support for custom translator

### ISSUE THREAD

**Issue by lchachurski** [willdurand/BazingaJsTranslationBundle#151]
JS translations seems to ignore custom Translator class. What I'm trying to do, is to display translation keys instead of translations to ease translation process. It works fine for standard translations, but not at all for JS ones. Setting defaultDomain to '' didn't help as well. Any hints?

``` yml
parameters:
    translator.class: Acme\HelloBundle\Translation\Translator
```

source: http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration

**Comment by herodrigues** [comment]
Have you tried to set the default domain to messages and put your translation files inside the Resources/translations folder of your bundle?

**Comment by chrifmarwen** [comment]
I have the same problem.

**Comment by stof** [comment]
I don't understand how the JS should use your custom class. This bundle does not use the Translator class at all (as it reimplements it in JS). The PHP side only uses the translation loading.

If you want to display translation keys rather than messages, you will need to overwrite the JS ``Translator`` variable with your own implementation.

**Comment by chrifmarwen** [comment]
There is acommand line that uses the translator finder to generate JS translation. So whenever our translation are defined it will find them using the config.yml.

**Comment by stof** [comment]
@chrifmarwen I don't understand what you mean. The JS translation files are generated by loading the translation catalogue with the loaders and dumping it as JSON or JS. It does *not* call the Translator.

**Comment by lchachurski** [comment]
Closing this one as @stof has a good point here.
