### ISSUE TITLE
[Doc] Is dumping needed when loading via bazinga_jstranslation_js?

### ISSUE THREAD

**Issue by andrerom** [willdurand/BazingaJsTranslationBundle#165]
[Documentation](https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md) is missing a complete example on what is expected in the end, and its hard to see what you needed, and what are alternatives to each-other.

**Comment by stof** [comment]
if you load translation using the controller, there is no need for dumping. Dumping is here to allow improving performance (a static file is served faster than having to boot Symfony, even when the controller takes the translations from the cache, and it can be combined with other JS assets)

**Comment by andrerom** [comment]
Thanks, this is what I assumed. I'll try to find time to propose a doc PR to clarify this.
