### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by bensampaio** [willdurand/BazingaJsTranslationBundle#170]
Would it be possible to publish the JS files to npm? I have a JS library shared by several symfony projects. The problem is that this library depends on the translator you created but the only way to use it has a dependency is by copying the js file directly into my library src which isn't very maintainable. What do you think? Thank you!

**Comment by willdurand** [comment]
Personally, I am not a fan of doing this since the JS is really tied to the bundle itself, but @monteiro is the boss now :)

**Comment by bensampaio** [comment]
You can still keep the JS in the bundle. If the `package.json` is in the `Resources` folder you can tell npm only to include the `js` and `public/js` folders. This way when the bundle is set as a dependency via npm only the JS files will be there.

**Comment by monteiro** [comment]
Like @willdurand said, the JS is tied to the bundle, so it is maybe strange to put it in NPM like it was an independent package. :( 

@bensampaio when you install the bundle, the javascript package is installed. Maybe I'm not understanding your usecase correctly.

**Comment by bensampaio** [comment]
@monteiro I have two PHP projects that depend on the same JS project. This JS project is in a separate repo and it depends on your `Translator`. The problem is that I have no need for `composer` on this JS repo, so I have no way of setting the translator as a dependency.

I think your JS is independent enough to be used separately as long as you pass information with the correct structure into it. It isn't PHP or Symfony dependent, I think. Correct me if I'm wrong here.

In any case, I'm not proposing for it to be removed from the bundle but for it to also be served via npm. Maybe I can make a PR and show what I mean?

**Comment by bensampaio** [comment]
I created the PR #173 with an example on how to configure the bundle for npm. The only thing missing is publishing it! Let me know what you think @monteiro.
