### ISSUE TITLE
V2.6.0 and PHP 5.3

### ISSUE THREAD

**Issue by JakeFr** [willdurand/BazingaJsTranslationBundle#181]
Hello,
Since v2.6.0, this bundle in not compatible with php 5.3 anymore.
No more Travis  on php 5.3
And short array syntax introduced in code base in PR #172 

The issue is that composer.json has no php constraint and old project using this bundle with constraint like "^2.0" will update to 2.6.0

**Comment by stof** [comment]
?

**Comment by JakeFr** [comment]
Issue updated, sorry

**Comment by monteiro** [comment]
@JakeFr you are right. In dump command. That array sintax should not be there. We will generate a fix for that.

**Comment by monteiro** [comment]
@JakeFr I did the PR. Plz review.  

The Travis of php 5.3 was removed from Travis because of compatibility problems with Travis itself.

**Comment by stof** [comment]
@monteiro the 5.3 environment on Travis works fine. And if the bundle wants to keep support for 5.3, it should use it. The environment causing issue is the old 5.3.3 one (no openssl support)
