### ISSUE TITLE
Minimized version of translator doesn't have semicolon at the end

### ISSUE THREAD

**Issue by thomas2411** [willdurand/BazingaJsTranslationBundle#195]
translator.min.js doesn't have semicolon at the end so it throws error:
`TypeError: (intermediate value)(...) is not a function`

**Comment by monteiro** [comment]
@thomas2411 which browser?

**Comment by monteiro** [comment]
@thomas2411 nevermind. I saw the error.

**Comment by thomas2411** [comment]
Firefox and Chrome on Mac OS X, localhost. Maybe it is due to my other settings like strict or sth. But when I put semicolon on the end, it works like a charm

**Comment by monteiro** [comment]
@thomas2411 I just generated again the translator.min.js and it looks good. I've verified the syntax as well.
