### ISSUE TITLE
remove dependency on @templating service

### ISSUE THREAD

**Issue by craigh** [willdurand/BazingaJsTranslationBundle#200]
regarding: http://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen

Is there a way to keep the options open as far as the universal approach of the `@templating` service but still allow a developer to remove it and only use `@twig` instead?

https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/config/services.xml#L16
https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Dumper/TranslationDumper.php#L15-L18

**Comment by stof** [comment]
As you only need to render Twig templates, using Twig directly is fine IMO

**Comment by craigh** [comment]
> As you only need to render Twig templates, using Twig directly is fine IMO

I do not understand your comment. My ticket points out that This bundle relies on the `@templating` service and therefore cannot use twig (only) as a first class citizen - meaning, when I use this bundle, I must call `templating` and not `twig`. I would rather do the latter if that is possible.

unless you are implying that I should override the engine service definition?

**Comment by craigh** [comment]
this ticket is closed by #213. thanks @pyrech
