### ISSUE TITLE
How to easily switch to dumped translations in production?

### ISSUE THREAD

**Issue by JindrichPilar** [willdurand/BazingaJsTranslationBundle#209]
I would like to load translations dynamically during development and from dumped files in production. 
The idea is I generate dump files before deploying and I don't load the translation route in production environment.
However I haven't managed to generate url that would work in both environments.

The dumper [uses locale as part of the domain name](https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Dumper/TranslationDumper.php#L193) which the provided route does not accept.

What is the best solution for this problem?

**Comment by monteiro** [comment]
Hi @JindrichPilar ,

The best way to do what you are saying is to generate the dump files and getting them using a <script src.

Example using a macro that I put in the layout.html.twig which is used by all pages:

```
{% macro import(domain, locale) %}
    <script src="{{ asset('js/translations/' ~ domain ~ '/' ~ locale ~ '.js' }}"></script>
{% endmacro %}
```
This macro will fetch from the path web/js/translations/...

Notes: Take into account that using a script src, the result will be cached. Make sure you have cache disabled in your chrome dev tools to always have the latest translations.

This way you don't need anything related with routing in your view.

**Comment by JindrichPilar** [comment]
Hi @monteiro,

Thank you for your quick response.

But if I understand correctly I will have to dump the translations manually after every change in them. 
My goal is to have translations loaded dynamically (without dumping) during development and from file in production.

**Comment by monteiro** [comment]
@JindrichPilar You would always need to do that. When you change any translations you need to execute again the static assets generation and clear your cache.

Translations in symfony are cached: http://symfony.com/doc/current/translation.html ("Each time you create a new translation resource (or install a bundle that includes a translation resource), be sure to clear your cache so that Symfony can discover the new translation resources:")

**Comment by JindrichPilar** [comment]
@monteiro  When adding new translation resource (domain file) yes. When adding new line to 
existing domain it works without manual cache clearing.

**Comment by monteiro** [comment]
👍
