### ISSUE TITLE
Use fallback value if translation is null

### ISSUE THREAD

**Issue by sod** [willdurand/BazingaJsTranslationBundle#214]
Symfony and Bazinga fallback implementation seems to differ.

* [Symony MessageCatalogue::get](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/MessageCatalogue.php#L108) checks via `php isset`, `isset` is **false** if value is null.
* [Bazinga has_message](https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/js/translator.js#L324-L338) checks via `js foo in bar`, `foo in bar` is **true** if value is null.

So given yaml:
```yaml
--- # messages.en.yml
foo: bar
```

```yaml
--- # messages.fr.yml
foo: ~
```

Given `locale_fallback = 'en'`, `locale = 'fr'` and `domain = 'messages'`:
* php/twig `{{ 'foo'|trans }}` outputs `string: bar`
* bazinga `Translate.trans('foo')` outputs `null`

Could it be possible to drop all null values by the dumper?

**Comment by LordOfFailling** [comment]
I found a workaround for this issue.
Try this:
`<script src="{{ url('bazinga_jstranslation_js',{"locales":app.request.locale~",en"}) }}"></script>`
Its seems that the Bundle prefer the "non-fallback" locale.
