### ISSUE TITLE
2.6.6 is not backward compatible with 2.6.5

### ISSUE THREAD

**Issue by poolerMF** [willdurand/BazingaJsTranslationBundle#242]
> [2018-02-27 16:16:59] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 2 passed to Bazinga\Bundle\JsTranslationBundle\Controller\Controller::__construct() must be an instance of Twig_Environment, instance of Symfony\Bundle\TwigBundle\TwigEngine given, called in .../app/cache/prod/appProdProjectContainer.php on line 398 and defined" at .../vendor/willdurand/js-translation-bundle/Controller/Controller.php line 76 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 2 passed to Bazinga\\Bundle\\JsTranslationBundle\\Controller\\Controller::__construct() must be an instance of Twig_Environment, instance of Symfony\\Bundle\\TwigBundle\\TwigEngine given, called in .../app/cache/prod/appProdProjectContainer.php on line 398 and defined at .../vendor/willdurand/js-translation-bundle/Controller/Controller.php:76)"} []
> [2018-02-27 16:17:05] request.INFO: Matched route "bazinga_jstranslation_js". {"route_parameters":{"_controller":"bazinga.jstranslation.controller:getTranslationsAction","domain":"messages","_format":"js","_route":"bazinga_jstranslation_js"},"request_uri":".../translations?locales=sk&v=3"} []

 "symfony/symfony": "2.7.18",

**Comment by stof** [comment]
AFAIK, the `twig` service has *never* been a TwigEngine instance (which is used by a different service).

Are you sure that you cleared your prod cache after the update of the bundle ? Using the new class definition with the old service definition (from the old cached container) could cause such issue.

**Comment by poolerMF** [comment]
@stof I'm sorry, you're right :) problem was in my cache
