### ISSUE TITLE
No translating with module bundler webpack

### ISSUE THREAD

**Issue by megadruck** [willdurand/BazingaJsTranslationBundle#244]
I am using symfony 3.4.11 with encore webpack.
The global translation is working, but if it is loaded via module like 
var Translator = require('bazinga-translator');

the response of Translator.trans('yes') is yes

**Comment by DrJele** [comment]
you can try my sugestion https://github.com/willdurand/BazingaJsTranslationBundle/issues/254#issuecomment-582000147
