### ISSUE TITLE
Response content in the Controller gets emptied. (line 183)

### ISSUE THREAD

**Issue by xeniasarapoff** [willdurand/BazingaJsTranslationBundle#249]
response ->setNotModified() actually set the content to null so I suggest to remove it, but that doesn't quite fix it, so I suggest to initialise the 

$content = $response->getContent();
And then resetting it before returning the response

$response->setContent($content); 
Just before returning the $response object.

**Comment by stof** [comment]
I don't understand what is the issue you have

**Comment by xeniasarapoff** [comment]
The content of the response gets set to null because this method (from the Response class)
vendor/symfony/http-foundation/Response.php:982
`setNotModified`
Sets content to null therefore the response content that gets return is sometimes emptied.

**Comment by stof** [comment]
and if the response returns a 3.4 because it is not modified, having no content is exactly what we want.

**Comment by xeniasarapoff** [comment]
But I still want to get the content of the response, now it gets overridden with null and i lose the content?

**Comment by xeniasarapoff** [comment]
How do i get the content of the cache files then? Not modified but I still want the content.

**Comment by xeniasarapoff** [comment]
never mind :) I'm calling the method on server side. Thanks for your help though. Nice tool!

**Comment by stof** [comment]
Well, if you want to get the response content on the server side, don't include request header telling the server that you already have the content in your cache if you don't have it :smile: 

I suggest you to close this issue, as it does not need to have a maintainer involved.

**Comment by xeniasarapoff** [comment]
Thank you! 💯
