### ISSUE TITLE
Support for ICU-based message formatting

### ISSUE THREAD

**Issue by stof** [willdurand/BazingaJsTranslationBundle#256]
Symfony 4.2 adds support for ICU-based message formatting, but using a special convention on the domain name (it will look for messages in this suffixed domain first, and format them using the ICU rules instead of the Symfony convention).

It would be great to support that for projects migrating to the new format (maybe using the JS Intl API to have part of the info, even though it does not have the high-level MessageFormatter yet)

**Comment by Ciloe** [comment]
Hi there !

Any informations about this issue ? Thanks

**Comment by videni** [comment]
I also like this feature, the  [formatjs](https://formatjs.io/github/) is very popular in frontend, it would be very nice if this bundle can be used with it together  seamlessly

**Comment by videni** [comment]
@stof, hi, do you solve this?  maybe you can share your code,  I also need this feature badly, thanks.

**Comment by stof** [comment]
no, I haven't done anything on this topic yet (I'm not yet using Symfony 4 in the project where I use this bundle, so I haven't migrated to ICU messages either, and so this is not a blocker for me. I opened this feature request as a community need rather than a personal need)

**Comment by timwhite** [comment]
This is something we need too. For now, we've got a `js` domain for messages we want in JS, and we don't use the ICU format for those. It would be nice to be able to use a consistent format though.
