### ISSUE TITLE
Deprecate PHP 5.x and PHP 7.0

### ISSUE THREAD

**Issue by monteiro** [willdurand/BazingaJsTranslationBundle#261]
Following the PHP supported versions table: http://php.net/supported-versions.php

I wonder if we can deprecate the PHP 5.x versions in this bundle.

**Comment by steveWinter** [comment]
Seems sensible to me - chances are if anyone's still running those PHP versions they will be using an older version of this, and many other libraries already.

**Comment by monteiro** [comment]
@steveWinter what about deprecate PHP 5.x versions? 

Don't really know the impact of this could have. We can create a major version to avoid them to update automatically with composer (if it's a minor version).

**Comment by ping-localhost** [comment]
Drop 5.6 and require 7.1, that way you are following Symfony.

**Comment by stof** [comment]
Dropping unmaintained PHP versions can even be done in a minor version. Composer will *not* update you automatically to an incompatible version thanks to the ` php`  requirement.

**Comment by vanputten** [comment]
5.6 gets dropped in #271 
7.1 has become the new minimal version (support for 3.4 has been preserved)
