### ISSUE TITLE
deprecated TreeBuilder::root() method 

### ISSUE THREAD

**Issue by thehatami** [willdurand/BazingaJsTranslationBundle#264]
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "bazinga_js_translation" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by bluser86** [comment]
Duplicates https://github.com/willdurand/BazingaJsTranslationBundle/issues/258

**Comment by vanputten** [comment]
Fixed in #271
