### ISSUE TITLE
TreeBuilder::root deprecated 

### ISSUE THREAD

**Issue by gazouweb** [willdurand/BazingaJsTranslationBundle#265]
Hello,
When will the fix be applied #258 to no longer have this warning with SF4.3?
Thank you ;)

**Comment by maxhelias** [comment]
There are already 2 issues on this topic and a PR. I think it's not necessary to open a 3rd..

**Comment by gazouweb** [comment]
Since January too ...

**Comment by migo315** [comment]
Well, I think this bundle is "End of Life". Just one commit in 2018, only one in 2019. Multiple pull requests for a deprecation which doesn't get merged. And without the deprecation fix this bundle cannot used with Symfony 5.0.

Does anyone has an alternative?

**Comment by vanputten** [comment]
This has been fixed in my PR #271 
@migo315 Symfony 5.0 support has also been added in the same PR

**Comment by migo315** [comment]
Great work @vanputten ! ;-)

But I can't test it. I replaced BazingaJsTranslationBundle with my own implementation (very simple use case).
