### ISSUE TITLE
Return value of "Bazinga\Bundle\JsTranslationBundle\Command\DumpCommand::execute()" must be of the type int, NULL returned.

### ISSUE THREAD

**Issue by drjele** [willdurand/BazingaJsTranslationBundle#278]
i get the error when running "php bin/console bazinga:js-translation:dump public/js/bazinga_jstranslation_js --format=json".

my setup:
PHP 7.4
Symfony 5
willdurand/js-translation-bundle: 3.0.0

**Comment by kl3sk** [comment]
waiting PR https://github.com/willdurand/BazingaJsTranslationBundle/pull/275

**Comment by stof** [comment]
@monteiro this should be closed as the PR has been merged.
