### ISSUE TITLE
Wrong domain name

### ISSUE THREAD

**Issue by dubitoph** [willdurand/BazingaJsTranslationBundle#298]
When I use this domain name `<script src="{{ url('bazinga_jstranslation_js', { 'domain': 'messages+intl-icu' }) }}"></script>`, I have this error : 

> An exception has been thrown during the rendering of a template ("Parameter "domain" for route "bazinga_jstranslation_js" must match "[\w]+" ("messages+intl-icu" given) to generate a corresponding URL.").

However, I need to use this name of file to manage plurals.

**Comment by stof** [comment]
use `messages` only, which loads both the `messages` and `messages+intl-icu` messages automatically (treating the `+intl-icu` as an internal implementation detail rather than a part of the public domain, as done when using `$translator->trans()` in Symfony)

**Comment by stof** [comment]
However, note that support for ICU-based formatting is available only in the dev version of the bundle, not in releases yet.

**Comment by dubitoph** [comment]
When I use "messages", the keys arent displayed without being translated.

**Comment by stof** [comment]
@dubitoph see my comment about needing the dev version. The 3.0.x releases don't support the ICU format for messages.

**Comment by monteiro** [comment]
Since we have released the last version 4.0.0 with ICU format support, I will close this issue. Feel free to re-open if the issue persists.
