### ISSUE TITLE
ICU pluralization documented but not in code?

### ISSUE THREAD

**Issue by tardnuk** [willdurand/BazingaJsTranslationBundle#301]
Hello, I can see in documentation, that there is pluralization using ICU mentioned. However it is not in current latest release v3.0.1.

Also when I downloaded only JS source for translator, it is not working properly even when I add intl-messageformat.

Do you have any plans of release date?

Thanks.

**Comment by stof** [comment]
It is only in the dev version for no, not released yet.
There's at least https://github.com/willdurand/BazingaJsTranslationBundle/pull/300 that need to be merged before the release, to avoid making a broken release. Fortunately, it is now ready.

But in any case, I'm not a maintainer (only a contributor) so I cannot do it myself.

**Comment by monteiro** [comment]
We have released the 4.0.0 version. Feel free to try it and report any issues. I will close this issue. Thanks @tardnuk and @stof for the support.
