### ISSUE TITLE
Dependency of compromised polyfill.io

### ISSUE THREAD

**Issue by shtumi** [willdurand/BazingaJsTranslationBundle#357]
According to investigation of sansec.io
https://sansec.io/research/polyfill-supply-chain-attack
the library polyfill.io became compromised and lead potential security risks of malware injection
[BazingaJsTranslationBundle](https://github.com/willdurand/BazingaJsTranslationBundle) contains link to polyfill.io in js/index.html
I guess need remove this legacy dependency by security reasons.

**Comment by karion** [comment]
https://github.com/willdurand/BazingaJsTranslationBundle/pull/359

**Comment by stof** [comment]
@monteiro this should be closed as the PR has been merged

**Comment by monteiro** [comment]
thanks a lot @stof

**Comment by AndreasA** [comment]
@stof @monteiro What about an official release/tag for the fix? as it currently is only available using dev-master. Sure it is only relevant if the template is used directly but still.

**Comment by monteiro** [comment]
@AndreasA absolutely. I will do during today.
